name: Install packages
description: Setup package-manager and install dependencies

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'
        registry-url: https://registry.npmjs.org
    - run: pnpm --version
      shell: bash
    - run: pnpm install --frozen-lockfile --prefer-offline
      shell: bash
    - name: Set SHAs
      uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0
    - run: |
        echo "BASE: ${{ env.NX_BASE }}"
        echo "HEAD: ${{ env.NX_HEAD }}"
      shell: bash
