name: 'Chromatic'
# Opt out of any default permissions, but allow read access to contents
permissions:
  contents: read

on: push

concurrency:
  group: chromatic-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: ks-no/github-actions-public/checkout@23507d99e1864f7eedfa91386a280356bbc93b7f # @11. aug 26
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install-packages

      - name: Run Chromatic
        uses: chromaui/action@14cfaef73576e69f95f47f60058063f46ca38719 # v18.1.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: false
          autoAcceptChanges: ${{ github.ref == 'refs/heads/main' }}
          onlyChanged: true
