name: 'Chromatic'
# Opt out of any default permissions, but allow read access to contents
permissions:
  contents: read

on: push

concurrency:
  group: chromatic-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install-packages

      - name: Run Chromatic
        uses: chromaui/action@a18e9f57b71eb05f941848c0b927aab2ee644e3e # v18.10.2
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: false
          autoAcceptChanges: ${{ github.ref == 'refs/heads/main' }}
          onlyChanged: true
          externals: |
            packages/themes/src/**
